obstacle_range: 2.5
raytrace_range: 3
footprint: [[0.15, 0.4], [0.15, -0.4], [-1, -0.4], [-1, 0.4]]
footprint_inflation: 0.1
#robot_radius: 0.3
inflation_radius: 0.45
max_obstacle_height: 3
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
